#!/bin/bash

echo "================================================================================"
echo "  SignalOrchestrator 통합 완료 - 메뉴 옵션 테스트"
echo "================================================================================"
echo ""

echo "1️⃣  도움말 확인"
echo "--------------------------------------------------------------------------------"
python3 main_auto_trading.py --help
echo ""

echo "2️⃣  사용 가능한 명령어"
echo "--------------------------------------------------------------------------------"
echo ""
echo "📋 백테스트 검증 모드:"
echo "   python3 main_auto_trading.py --dry-run --conditions 0,1,2"
echo ""
echo "   설명: 실제 매매 없이 L0-L6 시그널 파이프라인만 확인"
echo "   용도: 통합 후 검증, 조건식 테스트"
echo ""
echo "🚀 실전 투입 모드:"
echo "   python3 main_auto_trading.py --live --conditions 0,1,2,3,4,5"
echo ""
echo "   설명: 실제 매매 실행 (월요일 09:00 장 시작 시)"
echo "   용도: 실제 트레이딩"
echo ""
echo "⚡ 테스트 모드 (대기 건너뛰기):"
echo "   python3 main_auto_trading.py --skip-wait --conditions 0,1,2"
echo ""
echo "   설명: 스케줄 대기 없이 즉시 실행"
echo "   용도: 빠른 테스트"
echo ""
echo "================================================================================"
echo "  ✅ 메뉴 옵션 통합 완료!"
echo "================================================================================"
echo ""
echo "권장 실행 순서:"
echo "  1. python3 main_auto_trading.py --dry-run --conditions 0,1,2"
echo "     (백테스트로 L0-L6 파이프라인 검증)"
echo ""
echo "  2. python3 main_auto_trading.py --live --conditions 0,1,2,3,4,5"
echo "     (실전 투입)"
echo ""
